#!/bin/bash

echo "========================================="
echo "  Hermes WebUI APK 构建说明"
echo "========================================="
echo ""
echo "由于 Termux 环境限制，建议使用以下方式构建 APK："
echo ""
echo "方式 1：使用 Android Studio（推荐）"
echo "  1. 将 ~/HermesWebUI 目录复制到电脑"
echo "  2. 用 Android Studio 打开项目"
echo "  3. Build -> Build Bundle(s) / APK(s) -> Build APK(s)"
echo ""
echo "方式 2：使用 GitHub Actions（免费）"
echo "  1. 创建 GitHub 仓库"
echo "  2. 上传项目代码"
echo "  3. 使用 GitHub Actions 自动构建"
echo ""
echo "方式 3：使用在线 APK 构建服务"
echo "  - https://www.buildfire.com"
echo "  - https://gonative.io"
echo ""
echo "========================================="
echo "项目文件位置："
echo "  ~/HermesWebUI/"
echo ""
echo "需要复制的文件："
ls -la ~/HermesWebUI/app/src/main/java/com/hermes/webui/
echo ""
echo "========================================="
